name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Temporary Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'temp'

      - name: Checkout Temporary Branch
        uses: actions/checkout@v2
        with:
          ref: 'temp'

      - name: Bump Version
        run: |
          NEW_VERSION=$(echo ${POM_VERSION} | awk -F. '{ minor=$2+1; print $1"."minor"."$3}')
          echo  "New version: ${NEW_VERSION}"
          mvn versions:set -DnewVersion=${NEW_VERSION} -DgenerateBackupPoms=false
          git config --global user.email "release-bot@movingimage.com"
          git config --global user.name "Release Bot"
          git add .
          git commit -m "set version for next release: ${NEW_VERSION}"
          git push

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          base: temp

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.TECHNICAL_USER_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}"
