name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Temporary Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'temp'

      - name: Checkout Temporary Branch
        uses: actions/checkout@v3
        with:
          ref: 'temp'

      - name: Make Some Changes
        run: |
          echo "Hello" >> report.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Made Changes"
          git push

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: temp
          signoff: false
          draft: false
          delete-branch: false

      #- name: Approve Pull Request
      #  uses: juliangruber/approve-pull-request-action@v1
      #  with:
      #    github-token: ${{ secrets.TECHNICAL_USER_TOKEN }}
      #    number: ${{ steps.cpr.outputs.pull-request-number }}"
